package generator

import (
	"fmt"
	"strings"

	"github.com/iancoleman/strcase"

	"github.com/n25a/crafting-table/assets"
	"github.com/n25a/crafting-table/internal/structure"
)

func createTemplate(structure *structure.Structure, packageName, interfaceSyntax,
	createFunc, updateFunc, getFunc string) string {
	// TODO : add license header
	syntax := fmt.Sprintf(`
// Code generated by Crafting-Table.
// Source code: https://github.com/n25a/crafting-table

package %s

import (
	"context"
	"database/sql"
	"errors"

	"github.com/jmoiron/sqlx"
)

%s

var Err%sNotFound = errors.New("%s not found")

type mysql%s struct {
	db *sqlx.DB
}

func NewMySQL%s(db *sqlx.DB) %s {
	return &mysql%s{db: db}
}

%s

%s

%s
`,
		packageName,
		interfaceSyntax,
		structure.Name,
		strings.Replace(strcase.ToSnake(structure.Name), "_", " ", -1),
		structure.Name,
		structure.Name,
		structure.Name,
		structure.Name,
		createFunc,
		updateFunc,
		getFunc,
	)

	return syntax
}

func createFunctionRepository(structure *structure.Structure) (syntax, funcDeclare string, err error) {
	syntax, funcDeclare = assets.A.Sqlx.Insert(structure)
	return syntax, funcDeclare, nil
}

func getFunctionCreator(structure *structure.Structure, vars *[]structure.Variables) (syntax string, functions []string, err error) {

	body, header := assets.A.Sqlx.SelectAll(structure)

	syntax += body
	functions = append(functions, header)

	body, headers := assets.A.Sqlx.SelectBy(structure, vars)

	syntax += body
	for _, header := range headers {
		functions = append(functions, header)
	}

	return syntax, functions, nil
}

func updateFunctionCreator(structure *structure.Structure, updateVars *[]structure.UpdateVariables) (syntax string, functions []string, err error) {

	body, header := assets.A.Sqlx.UpdateAll(structure)

	syntax += body
	functions = append(functions, header)

	body, headers := assets.A.Sqlx.UpdateBy(structure, updateVars)

	syntax += body
	for _, header := range headers {
		functions = append(functions, header)
	}

	return syntax, functions, nil
}
